parameters:
    google_recaptcha.form.type.class: Google\RecaptchaBundle\Form\Type\RecaptchaType
    google_recaptcha.validator.true.class: Google\RecaptchaBundle\Validator\Constraints\TrueValidator

services:
    google_recaptcha.form.type:
        class:      "%google_recaptcha.form.type.class%"
        arguments:  [ "@service_container" ]
        tags:
            - { name: form.type, alias: google_recaptcha }

    google_recaptcha.validator.true:
        class:      "%google_recaptcha.validator.true.class%"
        arguments:  [ "@service_container" ]
        tags:
            - { name: validator.constraint_validator, alias: google_recaptcha.true }
