parameters:
    vihuvac_recaptcha.form.type.class: Vihuvac\Bundle\RecaptchaBundle\Form\Type\RecaptchaType
    vihuvac_recaptcha.validator.true.class: Vihuvac\Bundle\RecaptchaBundle\Validator\Constraints\TrueValidator

services:
    vihuvac_recaptcha.form.type:
        class:      "%vihuvac_recaptcha.form.type.class%"
        arguments:  [ "@service_container" ]
        tags:
            - { name: form.type, alias: vihuvac_recaptcha }

    vihuvac_recaptcha.validator.true:
        class:      "%vihuvac_recaptcha.validator.true.class%"
        arguments:  [ "@service_container" ]
        tags:
            - { name: validator.constraint_validator, alias: vihuvac_recaptcha.true }
